export const fakeData = [
  {
    ArticalId: "ABC123",
    ArticalDate: "2023-11-01",
    PublicationName: "Example Publication 1",
    Headlines: "Breaking News 1",
    PageNo: 5,
    PDFSize: "2.3 MB",
    ReportingSubject: "Subject A",
  },
  {
    ArticalId: "DEF456",
    ArticalDate: "2023-11-02",
    PublicationName: "Example Publication 2",
    Headlines: "Latest Updates 2",
    PageNo: 8,
    PDFSize: "3.1 MB",
    ReportingSubject: "Subject B",
  },
  {
    ArticalId: "GHI789",
    ArticalDate: "2023-11-03",
    PublicationName: "Example Publication 3",
    Headlines: "Important News 3",
    PageNo: 6,
    PDFSize: "1.8 MB",
    ReportingSubject: "Subject C",
  },
  {
    ArticalId: "ABC123",
    ArticalDate: "2023-11-01",
    PublicationName: "Example Publication 1",
    Headlines: "Breaking News 1",
    PageNo: 5,
    PDFSize: "2.3 MB",
    ReportingSubject: "Subject A",
  },
  {
    ArticalId: "DEF456",
    ArticalDate: "2023-11-02",
    PublicationName: "Example Publication 2",
    Headlines: "Latest Updates 2",
    PageNo: 8,
    PDFSize: "3.1 MB",
    ReportingSubject: "Subject B",
  },
  {
    ArticalId: "GHI789",
    ArticalDate: "2023-11-03",
    PublicationName: "Example Publication 3",
    Headlines: "Important News 3",
    PageNo: 6,
    PDFSize: "1.8 MB",
    ReportingSubject: "Subject C",
  },
  {
    ArticalId: "JKL012",
    ArticalDate: "2023-11-04",
    PublicationName: "Example Publication 4",
    Headlines: "Breaking Updates 4",
    PageNo: 7,
    PDFSize: "2.7 MB",
    ReportingSubject: "Subject D",
  },
  {
    ArticalId: "MNO345",
    ArticalDate: "2023-11-05",
    PublicationName: "Example Publication 5",
    Headlines: "News Alert 5",
    PageNo: 4,
    PDFSize: "1.5 MB",
    ReportingSubject: "Subject E",
  },
];
